PACKAGE_NAME="it87"
PACKAGE_VERSION="nasdisplay-a904dd88"
MAKE[0]="make TARGET=${kernelver} DRIVER_VERSION=nasdisplay-a904dd88"
BUILT_MODULE_NAME[0]="it87"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"
NO_WEAK_MODULES="yes"
