#!/usr/bin/env python3
"""Bake Dream UI Sans: 4-bit antialiased glyphs derived from Liberation Sans (OFL).

Runtime has no filesystem/font loading, and host previews use identical pixels.
Regenerate with Pillow; the committed header is all the firmware build needs.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'src/firmware/assets/fonts/source.ttf'
data, glyphs, fonts = [], [], []
for size in (14, 16, 20, 24, 30, 42, 78):
    font = ImageFont.truetype(str(source), size)
    chars = ''.join(chr(i) for i in range(32, 127)) if size <= 24 else ' -.0123456789%C'
    fonts.append((size, len(glyphs), len(chars)))
    for char in chars:
        l, t, r, b = font.getbbox(char, anchor='ls')
        w, h = r-l, b-t
        mask = Image.new('L', (max(1,w), max(1,h)))
        ImageDraw.Draw(mask).text((-l,-t), char, font=font, fill=255, anchor='ls')
        values = [int(p)*15//255 for p in mask.getdata()] if w*h else []
        glyphs.append((ord(char), len(data), w, h, l, t, round(font.getlength(char))))
        for i in range(0, len(values), 2):
            data.append((values[i]<<4) | (values[i+1] if i+1<len(values) else 0))
lines = ['// Generated by tools/generate_ui_font.py; Dream UI Sans, SIL OFL 1.1.',
         '// Source copyright/license: src/firmware/assets/fonts/LICENSE.txt', '#pragma once',
         'struct UiGlyph { uint8_t code; uint32_t offset; uint8_t w,h; int8_t x,y; uint8_t advance; };',
         'struct UiFont { uint8_t size; uint16_t start,count; };',
         'static const uint8_t uiPixels[] = {']
lines += [','.join(map(str,data[i:i+32]))+',' for i in range(0,len(data),32)]
lines += ['};', 'static const UiGlyph uiGlyphs[] = {']
lines += ['{'+','.join(map(str,g))+'},' for g in glyphs]
lines += ['};','static const UiFont uiFonts[] = {']
lines += ['{'+','.join(map(str,f))+'},' for f in fonts]
lines += ['};','']
(ROOT/'src/firmware/include/ui_font_data.h').write_text('\n'.join(lines))
print(f'Dream UI Sans: {len(data)} bitmap bytes, {len(glyphs)} glyphs')
